services:
  catalog_database:
    image: postgres
    container_name: atelie_db
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user -d catalog_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: app_user
      POSTGRES_DB: catalog_db
      POSTGRES_PASSWORD: app_password
    volumes:
      - pgdata:/var/lib/postgresql
    ports:
      - "5435:5432"

  catalog_api:
    build: .
    container_name: atelie_api
    image: atelie_catalog_api
    ports:
      - "8008:8000"
    depends_on:
      catalog_database:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg://app_user:app_password@catalog_database:5432/catalog_db
    # Carrega as outras variáveis (como SECRET_KEY) do .env
    env_file:
      - .env

volumes:
  pgdata: