"""alter tables products

Revision ID: 221820418f1e
Revises: 4fe1a2370409
Create Date: 2026-07-04 19:56:57.922421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '221820418f1e'
down_revision: Union[str, Sequence[str], None] = '4fe1a2370409'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_images', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('product_variations', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_variations', 'is_deleted')
    op.drop_column('product_images', 'is_deleted')
    # ### end Alembic commands ###
