"""create table outbox

Revision ID: 4fe1a2370409
Revises: c2404115deec
Create Date: 2026-07-04 19:17:32.573895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4fe1a2370409'
down_revision: Union[str, Sequence[str], None] = 'c2404115deec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox_logs',
    sa.Column('outbox_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('log_id', sa.String(length=50), nullable=False),
    sa.Column('aggregate_type', sa.String(length=50), nullable=False),
    sa.Column('aggregate_id', sa.String(length=50), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('outbox_id')
    )
    op.create_index(op.f('ix_outbox_logs_aggregate_id'), 'outbox_logs', ['aggregate_id'], unique=False)
    op.create_index(op.f('ix_outbox_logs_log_id'), 'outbox_logs', ['log_id'], unique=False)
    op.create_index(op.f('ix_outbox_logs_processed'), 'outbox_logs', ['processed'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outbox_logs_processed'), table_name='outbox_logs')
    op.drop_index(op.f('ix_outbox_logs_log_id'), table_name='outbox_logs')
    op.drop_index(op.f('ix_outbox_logs_aggregate_id'), table_name='outbox_logs')
    op.drop_table('outbox_logs')
    # ### end Alembic commands ###
