"""create stock_reservation

Revision ID: f9e15db01855
Revises: 08fe584a08dd
Create Date: 2026-06-14 21:53:56.937732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9e15db01855'
down_revision: Union[str, Sequence[str], None] = '08fe584a08dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_variant_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('expire', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'EXPIRED', 'CANCELED', name='reservationstatus'), nullable=False),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_reservation_order_id'), 'stock_reservation', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_reservation_order_id'), table_name='stock_reservation')
    op.drop_table('stock_reservation')
    # ### end Alembic commands ###
